### ISSUE TITLE
LTI and Quizlet

### ISSUE THREAD

**Issue by dkrefting** [instructure/lti_public_resources#6]
When I add the LIT URL of https://www.eduappcenter.com/configurations/7mqdncyidtkbrig1.xml  it tells me that site does not exist. Help.

**Comment by simonista** [comment]
Hi @dkrefting, thanks for the report, and sorry that no one ever got back to you. I'm doing some cleanup and realized that this repository has been forked internally, and development has gone forward on that fork, so I am going to archive this repository.

You might try sending this suggestion directly to [edu app center ](https://www.eduappcenter.com/)(see the little "?" icon in the bottom right corner), asking on the [canvas mailing list](https://groups.google.com/forum/#!forum/canvas-lms-users), or if you have a contract with Instructure, contacting your support rep.
