### ISSUE TITLE
Adding "?rel=0" to the embed URL (to disable display of "related videos") in the YouTube LTI app

### ISSUE THREAD

**Issue by hmcnally** [instructure/lti_public_resources#7]
It would be profoundly nice if this tool had the option to add "?rel=0" to the embed URL inserted into the page.  The "related video" list on YouTube is so often non-academic and inappropriate, so it seems like a natural thing to add.

**Comment by simonista** [comment]
Hi @hmcnally, thanks for the report, and sorry that no one ever got back to you. I'm doing some cleanup and realized that this repository has been forked internally, and development has gone forward on that fork, so I am going to archive this repository.

You might try sending this suggestion directly to [edu app center ](https://www.eduappcenter.com/)(see the little "?" icon in the bottom right corner), asking on the [canvas mailing list](https://groups.google.com/forum/#!forum/canvas-lms-users), or if you have a contract with Instructure, contacting your support rep.
