### ISSUE TITLE
SchoolTube LTI for Canvas

### ISSUE THREAD

**Issue by crhtex** [instructure/lti_public_resources#9]
When using the School Tube LTI it embeds an unsecure link. This is flagged in my Chrome browser. I can add the s to http to make it work in the html editor, but would like something more streamlined for my faculty.

**Comment by simonista** [comment]
Hi @crhtex, thanks for the report, and sorry that no one ever got back to you. I'm doing some cleanup and realized that this repository has been forked internally, and development has gone forward on that fork, so I am going to archive this repository.

You might try sending this suggestion directly to [edu app center ](https://www.eduappcenter.com/)(see the little "?" icon in the bottom right corner), asking on the [canvas mailing list](https://groups.google.com/forum/#!forum/canvas-lms-users), or if you have a contract with Instructure, contacting your support rep.
